linters:
  enable-all: true
linters-settings:
  goimports:
    local-prefixes: github.com/timeline
  gocritic:
    enabled-tags:
      - style
      - experimental

issues:
  timeout: 5m
  exclude-dirs:
    - "vendor"        # Пропускаем папку vendor для ускорения анализа
    - "third_party"   # Пропускаем папку с зависимостями от третьих лиц
  exclude:
    # False positive for table tests
    # https://github.com/kyoh86/scopelint/issues/4
    - Using the variable on range scope tt in function literal
  
output:
  formats: colored-line-number  # Вывод результатов в цветном виде с номерами строк
  # Лимит на количество одинаковых сообщений
  max-same-issues: 5