services:
  postgres:
    container_name: test-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: user
    networks:
        - testing
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5555 -U test"]
      interval: 1s
      retries: 3
      timeout: 5s

networks:
  testing:
    driver: bridge