version: '3'

services:
    postgres:
      container_name: postgres
      image: postgres:latest
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWD}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - "${DB_PORT}:5432"         
      #volumes:
      #  - ./db_init_user/:/docker-entrypoint-initdb.d/ 
      # - pgdata:/var/lib/postgresql/data
      networks:
        - default
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
        interval: 10s        
        timeout: 5s          
        retries: 5

#volumes:
#  pgdata:

networks:
  default:
    driver: bridge