{
 "title": "Request Counter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Кол-во потребляемой памяти (МБ)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes/(1000*1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время обработки запроса",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(backend_http_request_duration_seconds_sum[1m])) / sum(rate(backend_http_request_duration_seconds_count[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление процессорного времени приложением",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Число запросов в минуту",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(backend_http_requests_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}