global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend_server'

    scrape_interval: 10s
    scrape_timeout: 10s

    static_configs:
      - targets: ['host.docker.internal:8111']

  - job_name: 'analytic_server'

    scrape_interval: 10s
    scrape_timeout: 10s

    static_configs:
      - targets: ['host.docker.internal:10000']