global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ['localhost:${PROMETHEUS_PORT}']

  - job_name: "backend_app"

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ['host.docker.internal:${APP_HTTP_PORT}']