version: '3'

dotenv: ['.env']

vars:
  MODE: "{{default `` .MODE}}" # debug (only db), debug_metrics (db + metrics), dev (db, minio), dev_metrics (db, minio, metrics), prod (all)
  ENTRYPOINT: cmd/timeline/main.go
  SWAGGER_SRC: cmd/timeline/main.go
  PROJECT_ROOT: /home/${USER}/timeline/
  LINTER_OUT: linter.out
  APP_LOGS: logs/logs.txt
  SWAGGER_OUT: docs/swagger
  OUTPUT_BINARY: bin/timeline
  MIGRATION_MASTER_PATH: migrations/master
  MIGRATION_ANALYTICS_PATH: migrations/analytics
  # postgres://<user>:<password>@<host>:<port>/<dbname>?<params>
  MASTER_DSN: "{{.DB}}://{{.DB_USER}}:{{.DB_PASSWD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode={{.DB_SSLMODE}}"
  ANALYTICS_DSN: "{{.ANALYTICS_DB}}://{{.ANALYTICS_DB_USER}}:{{.ANALYTICS_DB_PASSWD}}@{{.ANALYTICS_DB_HOST}}:{{.ANALYTICS_DB_PORT}}/{{.ANALYTICS_DB_NAME}}?sslmode={{.ANALYTICS_DB_SSLMODE}}"
  TEST_DSN: "postgres://user:passwd@localhost:5555/testdb?sslmode=disable"
  ENVS:
    - CONFIG_PATH
    - DB
    - DB_USER
    - DB_PASSWD
    - DB_HOST
    - DB_PORT
    - DB_NAME
    - DB_SSLMODE
    - MAIL_HOST
    - MAIL_PORT
    - MAIL_USER
    - MAIL_PASSWD
    - SECRET_PATH

tasks:
  deploy:
    desc: "Smart deploying"
    cmds:
      - task: deploy_{{.MODE}}
      - #- nohup bash -c 'sleep 5; task img_upload' &> img_upload_logs.out &
  
  deploy_debug:
    desc: "mode: debug (only db)"
    deps: [check_envs, master_db, master_migrate_up, build]
    cmds:
      - ./{{.OUTPUT_BINARY}}

  deploy_debug_metrics:
    desc: "mode: debug+ (db + metrics)"
    deps: [check_envs, master_db, master_migrate_up, metrics, build]
    cmds:
      - ./{{.OUTPUT_BINARY}}

  deploy_dev:
    desc: "mode: debug+ (db, minio)"
    deps: [check_envs, master_db, minio, master_migrate_up, build]
    cmds:
      - ./{{.OUTPUT_BINARY}}

  deploy_dev_metrics:
    desc: "mode: debug+ (db, minio, metrics)"
    deps: [check_envs, master_db, minio, metrics, master_migrate_up, build]
    cmds:
      - ./{{.OUTPUT_BINARY}}

  deploy_prod:
    desc: "Production deployment (full setup)"
    deps: [check_envs, docker_all, full_migrate_up, build]
    cmds:
      - ./{{.OUTPUT_BINARY}}

  debug:
    desc: "run debugger"
    deps: [check-envs, master_db, migrate-up]
    cmds:
      - go build -gcflags="all=-N -l" -o bin/timeline ./cmd/timeline/main.go
      - dlv debug --headless --listen=:2345 --api-version=2 ./cmd/timeline

  full_migrate_up:
    desc: "migrations [applying...]"
    cmds:
      - task: master_migrate_up
      - task: analytic_migrate_up
  
  full_migrate_down:
    desc: "migrations [reverse...]"
    cmds:
      - task: master_migrate_down
      - task: analytic_migrate_down

  master_migrate_up:
    silent: true
    cmds:
      - go run ./cmd/migrator/main.go --dsn={{.MASTER_DSN}} --migrations-path={{.MIGRATION_MASTER_PATH}} --instance=master_db
  
  analytic_migrate_up:
    silent: true
    cmds:
      - go run ./cmd/migrator/main.go --dsn={{.ANALYTICS_DSN}} --migrations-path={{.MIGRATION_ANALYTICS_PATH}} --instance=analytics_db

  master_migrate_down:
    silent: true
    cmds:
      - migrate -database {{.MASTER_DSN}} -path {{.MIGRATION_MASTER_PATH}} down -all
  
  analytic_migrate_down:
    silent: true
    cmds:
      - migrate -database {{.ANALYTICS_DSN}} -path {{.MIGRATION_ANALYTICS_PATH}} down -all
  
  migrate_test_down:
    silent: true
    cmds:
      - migrate -database {{.TEST_DSN}} -path {{.MIGRATION_MASTER_PATH}} down -all

  master_db:
    cmds:
      - docker-compose up -d postgres_master

  minio:
    cmds:
      - docker-compose up -d minio
  
  metrics:
    cmds:
      - docker-compose up -d prometheus grafana

  docker_all:
    desc: "deploy all containers in .yml"
    cmds:
      - docker-compose up -d

  docker_rm_all:
    desc: "delete containers"
    cmds:
      - docker-compose down
      
  check_envs:
    desc: "checks that all required environment variables are set and non-empty"
    silent: true
    cmds:
      - for:
          var: ENVS
        cmd: |
          if [ -z "${{ .ITEM }}" ]; then
            echo "Error: env {{ .ITEM }} isn't set." >&2
            exit 1
          fi
      - echo "All required environment variables are set"

  img_upload:
    desc: "launch script that make requests to upload images to S3"
    silent: true
    vars:
      API_URL: "http://localhost:8100/v1/media"
      IMAGES_DIR: "internal/controller/s3/test-image"
    cmds:
      - |
        find {{.IMAGES_DIR}} -type f | while IFS= read -r FILE; do
          ENTITY_ID=$(dirname "$FILE" | awk -F/ '{print $(NF-1)}')
          ENTITY=$(dirname "$FILE" | awk -F/ '{print $NF}')

          echo "Uploading $FILE with entity=$ENTITY and entityID=$ENTITY_ID"

          curl -X POST "{{.API_URL}}" \
            -F "entity=$ENTITY" \
            -F "entityID=$ENTITY_ID" \
            -F "file=@$FILE"

          echo "===================================="
        done

  build:
    silent: true
    cmds:
      - go fmt ./...
      - go build -v -o {{.OUTPUT_BINARY}} {{.ENTRYPOINT}}
  
  run:
    desc: "run application"
    deps: [build]
    cmds:
      - ./{{.OUTPUT_BINARY}}

  clean:
    desc: "remove generated swagger docs, binary, and \".out\" files"
    silent: true
    cmds:
      - |
        find "{{.SWAGGER_OUT}}" -mindepth 1 -maxdepth 1 -type f -delete 2>/dev/null || true
        find "{{.SWAGGER_OUT}}" -mindepth 1 -maxdepth 1 -type d -delete 2>/dev/null || true
        find "{{.OUTPUT_BINARY}}" -mindepth 1 -maxdepth 1 -type f -delete 2>/dev/null || true
        find "{{.OUTPUT_BINARY}}" -mindepth 1 -maxdepth 1 -type d -delete 2>/dev/null || true
        find "{{.APP_LOGS}}" -delete 2>/dev/null || true  
        find . -name "*.out" -delete 2>/dev/null || true 
        find . -name "__*" -delete 2>/dev/null || true
        find "coverage.html" -delete 2>/dev/null || true 
        echo "cleanup!"
    
  swagger:
    desc: "generate swagger docs"
    cmds:
      - swag init -g {{.SWAGGER_SRC}} -o {{.SWAGGER_OUT}}

  lint:
    desc: "run GolangCI-Lint and save output to file"
    cmds:
      - golangci-lint run --color=always > {{.LINTER_OUT}}
  
  mocks:
    desc: "generate mocks for every domen"
    cmds:
      - mockery --all --dir ./internal/infrastructure/ --output ./mocks/infrastructure
      - mockery --all --dir ./internal/controller/ --output ./mocks/controller

  test_coverage:
    desc: "run tests and show coverage"
    cmds:
      - docker-compose -f docker-test-postgres-compose.yml up -d
      - go run ./cmd/migrator/main.go --dsn={{.TEST_DSN}} --migrations-path={{.MIGRATION_MASTER_PATH}} --instance=test_master
      - nohup bash -c 'sleep 30; echo "> stopped:" &> coverage_log.out; docker stop test-postgres; echo "> removed:" &>> coverage_log.out; docker rm test-postgres' &>> coverage_log.out &
      - go test -short -count=1 -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o ./coverage.html
      - rm coverage.out

  test_db:
    desc: "deploy db -> apply migrations -> run repo tests -> remove db"
    silent: true
    cmds:
      #- nohup bash -c 'sleep 4; echo "> stopped:" &> test_db_docker.out; docker stop test-postgres; echo "> removed:" &>> test_db_docker.out; docker rm test-postgres' &>> test_db_docker.out &
      - docker-compose -f docker-test-postgres-compose.yml up -d
      - go run ./cmd/migrator/main.go --dsn={{.TEST_DSN}} --migrations-path={{.MIGRATION_MASTER_PATH}} --instance=test_master
      #- go build -o ./bin/loader ./cmd/loader && ./bin/loader --dsn={{.TEST_DSN}} --instance=test_master
      - nohup bash -c 'sleep 60; echo "> cleaning...:" &> test_db_docker.out; task migrate_test_down' &>> test_db_docker.out &
      - go test -v -count=1 ./internal/infrastructure/database/postgres
  
  dsn:
    desc: "show db's connection-url"
    silent: true
    cmds:
      - echo {{.MASTER_DSN}}
      - echo {{.ANALYTICS_DSN}}
        
  default:
    cmds: 
      - task -ac
