version: '3'

dotenv: ['.env']

vars:
  ENTRYPOINT: ./cmd/timeline/
  OUTPUT_BINARY: bin/timeline
  LINTER_LOG: linter_logs
  SWAGGER_SRC: ./cmd/timeline/main.go
  SWAGGER_OUT: ./docs/swagger
  # postgres://<user>:<password>@<host>:<port>/<dbname>?<params>
  MIGRATION_PATH: ./migrations
  DSN: "{{.DB}}://{{.DB_USER}}:{{.DB_PASSWD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode={{.DB_SSLMODE}}"
  ENVS:
    - CONFIG_PATH
    - DB
    - DB_USER
    - DB_PASSWD
    - DB_HOST
    - DB_PORT
    - DB_NAME
    - DB_SSLMODE
    - MAIL_HOST
    - MAIL_PORT
    - MAIL_USER
    - MAIL_PASSWD
    - SECRET_PATH

tasks:
  dsn:
    silent: true
    cmds:
      - echo {{.DSN}}
  
  migrate-up:
    desc: "migrations [applying...]"
    silent: true
    cmds:
      - go run ./cmd/migrator/main.go --dsn={{.DSN}} --migrations-path={{.MIGRATION_PATH}}
  
  migrate-down:
    desc: "migrations [reverse...]"
    silent: true
    cmds:
      - migrate -database {{.DSN}} -path {{.MIGRATION_PATH}} down
      
  check-envs:
    desc: "checks that all required environment variables are set and non-empty"
    silent: true
    cmds:
      - for:
          var: ENVS
        cmd: |
          if [ -z "${{ .ITEM }}" ]; then
            echo "Error: env {{ .ITEM }} isn't set." >&2
            exit 1
          fi
      - echo "All required environment variables are set."

  docker-all:
    cmds:
      - docker-compose up -d

  docker-rm:
    cmds:
      - docker-compose down

  docker-s3:
    cmds:
      - docker-compose up minio -d

  docker-db:
    cmds:
      - docker-compose up postgres -d

  swagger:
    desc: "Generate Swagger docs"
    cmds:
      - swag init -g {{.SWAGGER_SRC}} -o {{.SWAGGER_OUT}}

  lint:
    desc: "Run GolangCI-Lint and save output to file"
    cmds:
      - golangci-lint run > {{.LINTER_LOG}}.txt

  build:
    silent: true
    cmds:
      - go fmt ./...
      - go build -v -o {{.OUTPUT_BINARY}} {{.ENTRYPOINT}}
  
  run:
    desc: "build -> run"
    deps: [build]
    cmds:
      - ./{{.OUTPUT_BINARY}}

  clean:
    desc: "Remove generated Swagger docs, binary, and linter log"
    cmds:
      - rm -r ./{{.SWAGGER_DOCS}}/*
      - rm -r ./{{.OUTPUT_BINARY}}/*
      - rm -r ./{{.LINTER_LOG}}/*

  deploy:
    desc: "envs -> db -> s3 -> migrations -> build -> run"
    deps: [check-envs, docker-all, migrate-up, build]
    cmds:
      - ./{{.OUTPUT_BINARY}}

  default:
    desc: "Default task - runs Swagger generation"
    cmds:
      - task: swagger
