
DROP TABLE IF EXISTS user_verify;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS orgs_verify;
DROP TABLE IF EXISTS workers;
DROPT TABLE IF EXISTS services;
DROP TABLE IF EXISTS timetable;
DROP TABLE IF EXISTS orgs;
