# example
app:
  env: DEV
  use_local_back_data: true
  enable_authorization: true
  http_server:
    host: localhost
    port: 8080
    timeout: 10s
    idle_timeout: 5m # connection ttl with client

token: 
  access_ttl: 1m
  refresh_ttl: 5m
