# example
app:
  env: DEV
  settings:
    use_local_back_data: true
    enable_authorization: false
    enable_media: false
    enable_mail: false
    enable_metrics: false
token: 
  access_ttl: 1m
  refresh_ttl: 5m
